sudo: false
dist: xenial
language: python
matrix:
  include:
    - python: "3.7"
install:
  - pip install mypy flake8 black
  - pip install -r requirements.txt
script:
  - mypy --strict -m authorizer
  - black --check -l 100 --target-version=py37 -v authorizer
  - flake8 --max-line-length=100 authorizer
